---
- name: Converge
  hosts: all
  vars:
    users:
      - name: foobar

    passwords:
      foobar: barfoo

  tasks:
    - name: "Include mslt.users"
      ansible.builtin.include_role:
        name: "msltwtf.users"
